In [1]:
import torch
import numpy as np

In [10]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.4054, 0.7251, 0.2151],
        [0.1978, 0.9720, 0.8928],
        [0.4074, 0.9365, 0.5093],
        [0.8927, 0.8734, 0.8483]])

In [11]:
type(tensor)

torch.Tensor

In [13]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.40542734, 0.7251395 , 0.21513695],
       [0.19777423, 0.9719644 , 0.8927584 ],
       [0.40738297, 0.93651235, 0.5092772 ],
       [0.8926914 , 0.87342876, 0.8482833 ]], dtype=float32)

In [14]:
type(numpy_from_tensor)

numpy.ndarray

In [16]:
torch.is_tensor(numpy_from_tensor)

False

In [18]:
numpy_from_tensor[0,0] = 100.0 #Both tensor and numpy instance share same memory
numpy_from_tensor, tensor

(array([[100.        ,   0.7251395 ,   0.21513695],
        [  0.19777423,   0.9719644 ,   0.8927584 ],
        [  0.40738297,   0.93651235,   0.5092772 ],
        [  0.8926914 ,   0.87342876,   0.8482833 ]], dtype=float32),
 tensor([[100.0000,   0.7251,   0.2151],
         [  0.1978,   0.9720,   0.8928],
         [  0.4074,   0.9365,   0.5093],
         [  0.8927,   0.8734,   0.8483]]))

In [22]:
numpy_arr = np.array([[1.0,2,3], [10,20,30], [100,200,300]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [23]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [24]:
 torc  h.is_tensor(tensor_from_numpy)

True

In [25]:
np_array_one = np.array([4,8])
np_array_one

array([4, 8])

In [28]:
tensor_from_array_one = torch.as_tensor(np_array_one) #Another way to convert np array to tensor and only performs copy when needed, else passes by memory reference
tensor_from_array_one 

tensor([4, 8])

In [38]:
 np_array_one[1] = 100
 np_array_one, tensor_from_array_one #This shows that it performs copy only when needed

(array([  4, 100]), tensor([  4, 100]))

In [34]:
np_array_two = np.array([2,2])
np_array_two

array([2, 2])

In [35]:
tensor_from_array_two = torch.tensor(np_array_two)
tensor_from_array_two

tensor([2, 2])

In [37]:
np_array_two[1] = 4
np_array_two, tensor_from_array_two

(array([2, 4]), tensor([2, 2]))