In [105]:
import torch 

In [106]:
tensor1 = torch.Tensor([[1,2,3], [4,5,6]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [107]:
tensor2 = torch.Tensor([[7,8,9], [10,11,12]])
tensor2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [108]:
tensor1.requires_grad

False

In [109]:
tensor2.requires_grad

False

In [110]:
tensor1.requires_grad_() #Enables tracking history on this tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [111]:
print(tensor1.grad) #No gradients available. This tensor is part of a graph but no forward and backward passes has been made

None


In [112]:
print(tensor1.grad_fn)

None


In [113]:
output_tensor = tensor1 * tensor2
output_tensor

tensor([[ 7., 16., 27.],
        [40., 55., 72.]], grad_fn=<MulBackward0>)

In [114]:
output_tensor.requires_grad #This is true because one of its inputs are ture

True

In [115]:
print(output_tensor.grad)

None


In [116]:
print(output_tensor.grad_fn ) #Grad function is multiplication because this tensor was produced by multiplication

In [117]:
output_tensor = (tensor1 * tensor2).mean()
print(output_tensor.grad_fn) #Grad function is mean because this tensor was produced by mean

In [118]:
print(tensor1.grad) #No gradient associated with tensor1, because no back pass has occured

None


In [119]:
output_tensor.backward()

In [120]:
print(tensor1.grad) #This gradient is partial derivative for parameters in tensor1 wrt to output_tensor

tensor([[1.1667, 1.3333, 1.5000],
        [1.6667, 1.8333, 2.0000]])


In [121]:
tensor1.grad.shape, tensor1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [122]:
print(tensor2.grad) #requires_grad is false so no gradient were calculate wrt tensor2

None


In [123]:
print(output_tensor.grad) #No gradient because this is the value wrt which we calculated partial derivatives to get our gradients

None


In [124]:
new_tensor = tensor1 * 3
print(new_tensor.requires_grad)

True


In [125]:
new_tensor

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)

In [126]:
with torch.no_grad(): #Stop autograd from trackin history on tensors with requires_grad = True
    new_tensor = tensor1 * 3
    print('new_tensor = ', new_tensor)
    print('requires_grad for tensor1 = ', tensor1.requires_grad)
    print('requires_grad for tensor2 = ', tensor2.requires_grad)
    print('requires_grad for new_tensor = ', new_tensor.requires_grad)

new_tensor =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
requires_grad for tensor1 =  True
requires_grad for tensor2 =  False
requires_grad for new_tensor =  False


In [127]:
def calculate(t):
    return t * 2

In [128]:
@torch.no_grad() #Tursn off history tracking for tensors created with this function
def calculate_with_no_grad(t):
    return t * 2

In [129]:
result_tensor = calculate(tensor1)
result_tensor

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)

In [130]:
result_tensor.requires_grad

True

In [131]:
result_tensor_no_grad = calculate_with_no_grad(tensor1)
result_tensor_no_grad

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [132]:
result_tensor_no_grad.requires_grad

False

In [133]:
with torch.no_grad():
    new_tensor_no_grad = tensor1 * 3
    print('new_tensor_no_grad = ', new_tensor_no_grad)
    with torch.enable_grad(): #Enables tracking within a block that disables traking
        new_tensor_grad = tensor1 * 3
        print('new_tensor_grad = ', new_tensor_grad)

new_tensor_no_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
new_tensor_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)


In [134]:
tensor_one = torch.tensor([[1.0,2.0], [3.0,4.0]], requires_grad=True)
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [135]:
tensor_two = torch.Tensor([[5,6], [7,8]])
tensor_two

tensor([[5., 6.],
        [7., 8.]])

In [136]:
tensor_two.requires_grad_()

tensor([[5., 6.],
        [7., 8.]], requires_grad=True)

In [137]:
final_tensor  = (tensor_one + tensor_two).mean()
final_tensor

tensor(9., grad_fn=<MeanBackward0>)

In [138]:
final_tensor.backward() #Calculates back pass for both inputs since they have grad tracking to True

In [141]:
tensor_one.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

In [140]:
tensor_two.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

In [143]:
detached_tensor = tensor_one.detach() #Returns a new tensor detached from current computation graph. Will set requires_grad=False
detached_tensor 

tensor([[1., 2.],
        [3., 4.]])

In [144]:
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [145]:
mean_tensor = (tensor_one + detached_tensor).mean()
mean_tensor.backward()

In [146]:
tensor_one.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [147]:
print(detached_tensor.grad)

None
