In [3]:
import torch
from torch.autograd import Variable

In [4]:
var = Variable(torch.FloatTensor([9]))
var

tensor([9.])

In [5]:
var.requires_grad

False

In [6]:
var.requires_grad_()

tensor([9.], requires_grad=True)

In [7]:
w1 = Variable(torch.FloatTensor([3]), requires_grad=True) 
w2 = Variable(torch.FloatTensor([7]), requires_grad=True)

w1,w2

(tensor([3.], requires_grad=True), tensor([7.], requires_grad=True))

In [8]:
result_var = var * w1
result_var

tensor([27.], grad_fn=<MulBackward0>)

In [9]:
result_var.requires_grad

True

In [10]:
result_var.backward()

In [12]:
w1.grad

tensor([9.])

In [14]:
print(w2.grad) #is None because it was not involved in the operation

None


In [18]:
var.grad

tensor([3.])