In [12]:
import torch

print(torch.__version__)

1.5.1


In [13]:
torch.get_default_dtype()  

torch.float64

In [14]:
torch.set_default_dtype(torch.float64)

In [15]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [16]:
torch.is_tensor(tensor_arr)

True

In [17]:
torch.numel(tensor_arr)

6

In [18]:
tensor_uninitialized = torch.Tensor(2,2)
tensor_uninitialized

tensor([[4.6395e-310, 5.4347e-323],
        [6.9039e-310, 4.6395e-310]])

In [19]:
tensor_uninitialized = torch.rand(2,2)
tensor_uninitialized

tensor([[0.3990, 0.6677],
        [0.9186, 0.8474]])

In [20]:
tensor_int = torch.tensor([5,3]).type(torch.IntTensor) #Creates int tensor on CPU only
tensor_int

tensor([5, 3], dtype=torch.int32)

In [21]:
#tensor_int_gpu = torch.tensor([5,3]).type(torch.cuda.IntTensor) #Creates int tensor on GPU only
#tensor_int_gpu

In [23]:
tensor_short = torch.ShortTensor([1.0,2.0,3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [24]:
tensor_float = torch.tensor([1.0,2.0,3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [30]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [31]:
tensor_of_ones = torch.ones([2,4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [32]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [33]:
tensor_eye = torch.eye(5) #5 x 5 tensor with diagonal elements of one
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [34]:
non_zero = torch.nonzero(tensor_eye) #Gives indeces of non zero elements in tensor
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [35]:
i = torch.tensor([[0,1,1], [2,2,0]]) #makes copy(not view) of passed tensor into new variable
i

tensor([[0, 1, 1],
        [2, 2, 0]])

In [38]:
v = torch.tensor([3,4,5], dtype=torch.float32)
v

tensor([3., 4., 5.], dtype=torch.float32)

In [39]:
sparse_tensor = torch.sparse_coo_tensor(i,v,[2,5])
sparse_tensor

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)