In [2]:
import torch

print(torch.__version__)

1.5.1+cpu


In [3]:
torch.get_default_dtype()  

torch.float32

In [4]:
torch.set_default_dtype(torch.float64)

In [5]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
torch.is_tensor(tensor_arr)

True

In [7]:
torch.numel(tensor_arr)

6

In [8]:
tensor_uninitialized = torch.Tensor(2,2)
tensor_uninitialized

tensor([[6.9212e-310, 4.6592e-310],
        [1.5810e-322, 6.3240e-322]])

In [9]:
tensor_uninitialized = torch.rand(2,2)
tensor_uninitialized

tensor([[0.7416, 0.9383],
        [0.5044, 0.1516]])

In [10]:
tensor_int = torch.tensor([5,3]).type(torch.IntTensor) #Creates int tensor on CPU only
tensor_int

tensor([5, 3], dtype=torch.int32)

In [11]:
#tensor_int_gpu = torch.tensor([5,3]).type(torch.cuda.IntTensor) #Creates int tensor on GPU only
#tensor_int_gpu

In [12]:
tensor_short = torch.ShortTensor([1.0,2.0,3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [13]:
tensor_float = torch.tensor([1.0,2.0,3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [14]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [15]:
tensor_of_ones = torch.ones([2,4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [16]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [17]:
tensor_eye = torch.eye(5) #5 x 5 tensor with diagonal elements of one
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
non_zero = torch.nonzero(tensor_eye) #Gives indeces of non zero elements in tensor
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [19]:
i = torch.tensor([[0,1,1], [2,2,0]]) #makes copy(not view) of passed tensor into new variable
i

tensor([[0, 1, 1],
        [2, 2, 0]])

In [20]:
v = torch.tensor([3,4,5], dtype=torch.float32)
v

tensor([3., 4., 5.], dtype=torch.float32)

In [21]:
sparse_tensor = torch.sparse_coo_tensor(i,v,[2,5])
sparse_tensor

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [22]:
 initial_tensor = torch.rand(2,3)
 initial_tensor

tensor([[0.8860, 0.6002, 0.9963],
        [0.0619, 0.4882, 0.8731]])

In [23]:
initial_tensor.fill_(10) #tensor.operation_ is an implace operation

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [24]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [25]:
 initial_tensor.add_(8)
 initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [26]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [27]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [28]:
tensor_chunk = torch.chunk(x, 3, 0) #Splits tensor into specified parts(arg2) and dimensions(arg3)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [29]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = tensor_chunk[2]

torch.cat((tensor1, tensor2, tensor3), 0)

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [30]:
random_tensor = torch.Tensor([[10, 8, 30], [40,5,6], [12,2,21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [31]:
random_tensor[0, 1] #Access specific elements

tensor(8.)

In [32]:
 random_tensor[1:, 1:] #Array slicing operation

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [33]:
random_tensor.size()

torch.Size([3, 3])

In [34]:
resized_tensor = random_tensor.view(9) #Passes by memory reference
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [35]:
resized_tensor.size()

torch.Size([9])

In [36]:
random_tensor[2,2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [37]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [38]:
random_tensor.shape

torch.Size([3, 3])

In [39]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2) #Creating additional dimensions
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [40]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [41]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [42]:
tensor_transpose = torch.transpose(initial_tensor, 0 , 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [43]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [44]:
sorted_tensor, sorted_indeces = torch.sort(random_tensor) #Sort method returns two values
sorted_indeces,sorted_tensor

(tensor([[1, 0, 2],
         [1, 2, 0],
         [1, 0, 2]]),
 tensor([[  8.,  10.,  30.],
         [  5.,   6.,  40.],
         [  2.,  12., 100.]]))

In [45]:
tensor_float = torch.FloatTensor([-1.1,-2.2,3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [46]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [1]:
rand1 = torch.abs(torch.randn(2,3)) #The .randn method returns random negative tensors
rand2 = torch.abs(torch.randn(2,3))
rand1, rand2

NameError: name 'torch' is not defined

In [48]:
add1 = rand1 + rand2
add1

tensor([[0.5359, 1.6470, 2.8918],
        [1.3843, 0.6402, 2.7556]])

In [49]:
add2 = torch.add(rand1, rand2)
add2

tensor([[0.5359, 1.6470, 2.8918],
        [1.3843, 0.6402, 2.7556]])

In [50]:
tensor = torch.Tensor([[-1,-2,-3], [1,2,3]])

In [51]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [52]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [53]:
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2) #Sets a limit for tensor elements
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [54]:
t1 = torch.Tensor([1,2])
t2 = torch.Tensor([10,20])

In [55]:
dot_product = torch.dot(t1, t2) #Performs matrix dot product
dot_product

tensor(50.)

In [56]:
matrix = torch.Tensor([[1,2,3], [4,5,6]])
vector = torch.Tensor([0,1,2])

In [57]:
matrix_vector  = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

In [58]:
andother_matrix = torch.Tensor([[10,30], [20,0], [0,50]])

In [59]:
matrix_mul = torch.mm(matrix, andother_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

In [60]:
torch.argmax(matrix_mul, dim=1) #Returns position of largest element along a dimension

tensor([1, 1])

In [61]:
torch.argmin(matrix_mul, dim=1) #Returns position of smallest element along a dimension

tensor([0, 0])